name: 'generate-pacman-game-from-github-contribution-grid'
description: 'Generates a Pacman game from a github user contributions grid. Output the animation as svg'
author: 'DuyetBKU'

runs:
    using: node20
    main: github-action/dist/index.js

inputs:
    github_user_name:
        description: 'github user name'
        required: true
    github_token:
        description: 'github token used to fetch the contribution calendar. Default to the action token if empty.'
        required: false
        default: ${{ github.token }}
    theme:
        description: 'Game theme (github, github-dark, dracula, monokai, react-light, react-dark, etc.)'
        required: false
        default: 'github'
    music:
        description: 'Enable game music (true or false)'
        required: false
        default: 'false'
